# Generated by Django 5.0.7 on 2024-07-22 21:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('img_src', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=100)),
                ('debut', models.IntegerField()),
                ('members', models.IntegerField()),
                ('popularity', models.IntegerField()),
                ('gender', models.CharField(max_length=100)),
                ('genre', models.CharField(max_length=100)),
                ('city_flag', models.CharField(max_length=100)),
                ('city_name', models.CharField(max_length=100)),
            ],
        ),
    ]
