import uuid

from django.db import models


class Artist(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)  # Generated by API
    img_src = models.CharField(
        max_length=200)  # Use https://png.pngtree.com/png-clipart/20210129/ourmid/pngtree-blue-default-avatar-png-image_2813123.jpg
    name = models.CharField(max_length=100)  # Brazilian artist name
    debut = models.IntegerField()  # Integer representing the year of band/artist begin
    members = models.IntegerField()  # Integer showing the number of members of the artist/band
    popularity = models.IntegerField()  # Integer showing the popularity rank based on brasil music consumption
    gender = models.CharField(max_length=100)  # Can be male/female or mixed
    genre = models.CharField(max_length=100)  # The overall genre of the artist/band
    city_flag = models.CharField(max_length=100)  # Use https://datampe.sebrae.com.br/images/icons/state/state_35.png
    city_name = models.CharField(max_length=100)  # City where artist begun the career.

    def __str__(self):
        return self.name
